# Generated by Django 5.2.5 on 2025-09-25 07:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s\\-\\(\\)]+$', 'Enter a valid phone number.')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('language', models.CharField(blank=True, max_length=64)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'created_at'], name='leads_lead_owner_i_d1bf3a_idx'), models.Index(fields=['owner', 'email'], name='leads_lead_owner_i_2e7e70_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('phone_number', ''), _negated=True), fields=('owner', 'phone_number'), name='unique_owner_phone_number')],
            },
        ),
    ]
