# Generated by Django 5.2.5 on 2025-10-13 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_owner_lead_unique_unowned_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{7,14}$', 'Enter a valid E.164 number like +14155550123.')]),
        ),
    ]
