# Generated by Django 5.2.5 on 2025-09-25 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=128, unique=True)),
                ('agent_id', models.CharField(blank=True, max_length=128, null=True)),
                ('user_display_name', models.CharField(blank=True, default='Visitor', max_length=255)),
                ('status', models.CharField(blank=True, default='completed', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('transcript_text', models.TextField(blank=True, default='')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='calls/support/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CallTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('role', models.CharField(max_length=10)),
                ('text', models.TextField(blank=True, default='')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='calls/turns/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='voices.callsession')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='My Voice', max_length=120)),
                ('eleven_voice_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='callsession',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='voices.voiceprofile'),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleven_agent_id', models.CharField(max_length=64)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='voices.voiceprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='voice_samples/')),
                ('duration_seconds', models.FloatField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='voices.voiceprofile')),
            ],
        ),

        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['conversation_id'], name='voices_call_convers_778afa_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['started_at'], name='voices_call_started_b79a64_idx'),
        ),
    ]
