# Generated by Django 5.2.5 on 2025-09-25 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddableAgent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(default='Website Assistant', max_length=120)),
                ('website_origin', models.CharField(max_length=255)),
                ('voice_id', models.CharField(max_length=128)),
                ('prompt', models.TextField(blank=True, default='')),
                ('language', models.CharField(default='en', max_length=8)),
                ('eleven_agent_id', models.CharField(blank=True, default='', max_length=128)),
                ('public_id', models.CharField(max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeds', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeds', to='voices.voiceprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'profile'), name='uniq_embed_per_owner_profile')],
            },
        ),
    ]
