# Generated by Django 5.2.5 on 2025-10-06 04:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0002_embeddableagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceprofile',
            name='language',
            field=models.CharField(default='English', max_length=120),
        ),
        migrations.AddField(
            model_name='voiceprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
