# Generated by Django 5.2.5 on 2025-10-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0003_voiceprofile_language_voiceprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddableagent',
            name='font_family',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='embeddableagent',
            name='modes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='embeddableagent',
            name='theme_color',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
