# Generated by Django 5.2.5 on 2025-10-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0004_embeddableagent_font_family_embeddableagent_modes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
