# Generated by Django 5.2.5 on 2025-10-13 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0005_alter_voiceprofile_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='embeddableagent',
            name='source_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='voiceprofile',
            name='eleven_agent_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='voices.voiceprofile'),
        ),
        migrations.AlterField(
            model_name='embeddableagent',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Arabic', 'Arabic')], default='English', max_length=8),
        ),
        migrations.CreateModel(
            name='TempClone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='voice_temp/')),
                ('language', models.CharField(default='en', max_length=8)),
                ('display_name', models.CharField(default='', max_length=120)),
                ('eleven_voice_id', models.CharField(blank=True, max_length=64, null=True)),
                ('eleven_agent_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_clones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
