# Generated by Django 5.2.5 on 2025-10-13 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0006_agent_is_system_embeddableagent_source_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='embed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='voices.embeddableagent'),
        ),
    ]
