# Generated by Django 5.2.5 on 2025-09-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cs_service_agent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='outbound_calling',
            field=models.BooleanField(default=True),
        ),
    ]
