# Generated by Django 5.2.5 on 2025-10-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_cs_service_agent_user_outbound_calling'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
