# Generated by Django 5.2.5 on 2025-10-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_address_user_country_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2, e.g. US', max_length=100),
        ),
    ]
