# Generated by Django 5.2.5 on 2025-10-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cs_use_vai_database',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='outbound_customization',
            field=models.BooleanField(default=True),
        ),
    ]
