# Generated by Django 5.2.5 on 2025-09-25 07:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('number', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('enabled', 'Enabled'), ('disabled', 'Disabled')], default='pending', max_length=16)),
                ('provider', models.CharField(choices=[('twilio', 'Twilio'), ('sip', 'SIP Trunk'), ('telnyx', 'Telnyx'), ('vonage', 'Vonage')], default='twilio', max_length=16)),
                ('provider_phone_id', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_number_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'created_at'], name='phone_numbe_owner_i_0349be_idx'), models.Index(fields=['owner', 'status'], name='phone_numbe_owner_i_b97183_idx'), models.Index(fields=['owner', 'country'], name='phone_numbe_owner_i_ec4705_idx'), models.Index(fields=['provider'], name='phone_numbe_provide_f0d1cc_idx')],
            },
        ),
    ]
