# Generated by Django 5.2.5 on 2025-10-09 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumberrequest',
            name='assigned_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phonenumberrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_phone_number_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phonenumberrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phonenumberrequest',
            name='number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='phonenumberrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('enabled', 'Enabled'), ('disabled', 'Disabled')], default='pending', max_length=16),
        ),
        migrations.AddIndex(
            model_name='phonenumberrequest',
            index=models.Index(fields=['status'], name='phone_numbe_status_fae719_idx'),
        ),
        migrations.AddIndex(
            model_name='phonenumberrequest',
            index=models.Index(fields=['number'], name='phone_numbe_number_956dd1_idx'),
        ),
    ]
