# Generated by Django 5.2.5 on 2025-10-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0002_phonenumberrequest_assigned_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('enabled', 'Enabled'), ('disabled', 'Disabled'), ('suspended', 'Suspended')], default='pending', max_length=16),
        ),
    ]
