"""
Django settings for vai project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
from datetime import timedelta

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default="django-insecure-oe(^o@^-zu##xu07jr9@hq9my*xa1eu6if8d5gwxpi#yc#jf&%")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["127.0.0.1", "localhost", "api.app.vai.gt-ai.io","apistaging.app.vai.gt-ai.io"])
APPEND_SLASH = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    "corsheaders",
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vai.accounts',
    "vai.phone_numbers",
    'vai.leads',
    'vai.lists',
    'vai.billing',
    'vai.campaigns',
    "rest_framework",
    "voices",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200",
    "https://vai.xob-webservices.com",
    "https://app.vai.gt-ai.io",
    "https://admin.vai.gt-ai.io",
    "https://staging.admin.vai.gt-ai.io",
    "https://staging.app.vai.gt-ai.io"
]

CORS_ALLOW_CREDENTIALS = True

AUTH_USER_MODEL = "accounts.User"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "accounts:login"          # replace later with your dashboard
LOGOUT_REDIRECT_URL = "accounts:login"
# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "handlers": {
#         "file": {
#             "level": "INFO",
#             "class": "logging.FileHandler",
#             "filename": "/var/log/gunicorn_vai/django.log",
#         },
#         "console": {
#             "class": "logging.StreamHandler",
#         },
#     },
#     "loggers": {
#         "django": {
#             "handlers": ["file", "console"],
#             "level": "INFO",
#             "propagate": True,
#         },
#         "webhooks.elevenlabs": {
#             "handlers": ["file", "console"],
#             "level": "INFO",
#             "propagate": False,
#         },
#     },
# }


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env("MAIL_HOST", default=env("EMAIL_HOST", default=""))
EMAIL_PORT = env.int("MAIL_PORT", default=env.int("EMAIL_PORT", default=587))
EMAIL_HOST_USER = env("MAIL_USERNAME", default=env("EMAIL_HOST_USER", default=""))
EMAIL_HOST_PASSWORD = env("MAIL_PASSWORD", default=env("EMAIL_HOST_PASSWORD", default=""))
_enc = env("MAIL_ENCRYPTION", default=env("EMAIL_ENCRYPTION", default="tls")).lower()
EMAIL_USE_SSL = _enc == "ssl"
EMAIL_USE_TLS = _enc == "tls"
DEFAULT_FROM_EMAIL = env("MAIL_FROM_ADDRESS", default=env("EMAIL_FROM_ADDRESS", default="no-reply@example.com"))
EMAIL_TIMEOUT = env.int("MAIL_TIMEOUT", default=10)
SERVER_EMAIL = DEFAULT_FROM_EMAIL
FRONTEND_DOMAIN = env("FRONTEND_DOMAIN", default="https://app.vai.gt-ai.io")

CORS_ALLOW_ALL_ORIGINS = env.bool("CORS_ALLOW_ALL_ORIGINS", default=False)
# CSRF_TRUSTED_ORIGINS = ["http://localhost:5173", "http://localhost:3000","http://localhost:4200", "http://127.0.0.1:4200","https://vaiapi.xob-webservices.com"]

MEDIA_URL = "/media/"
MEDIA_ROOT = env("MEDIA_ROOT", default=str(BASE_DIR / "media"))

# CSRF_TRUSTED_ORIGINS = [
#     # "https://your-frontend-domain.com",  # add when you hook real frontend
# ]

ROOT_URLCONF = 'vai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "django.template.context_processors.debug",
            ],
        },
    },
]

WSGI_APPLICATION = 'vai.wsgi.application'

#DRF default auth/formatting
# REST_FRAMEWORK = {
#     "DEFAULT_AUTHENTICATION_CLASSES": [
#         "rest_framework_simplejwt.authentication.JWTAuthentication",
#         "rest_framework.authentication.SessionAuthentication",
#     ],
#     "DEFAULT_PARSER_CLASSES": [
#         "rest_framework.parsers.JSONParser",
#         "rest_framework.parsers.FormParser",
#         "rest_framework.parsers.MultiPartParser",
#         "rest_framework.permissions.IsAuthenticated",
#     ],
# }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": env.str("DB_DATABASE", default="app"),
#         "USER": env.str("DB_USERNAME", default="user"),
#         "PASSWORD": env.str("DB_PASSWORD", default="secret"),
#         "HOST": env.str("DB_HOST", default="db"),
#         "PORT": env.int("DB_PORT", default=3306),
#         "OPTIONS": {
#             "charset": "utf8mb4",
#             "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }



DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_DATABASE"),
        "USER": env("DB_USERNAME"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
        "OPTIONS": {"charset": "utf8mb4"},
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", "OPTIONS": {"min_length": 8}},
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
# REST_FRAMEWORK = {
#     "DEFAULT_THROTTLE_CLASSES": [
#         "rest_framework.throttling.ScopedRateThrottle",
#     ],
#     "DEFAULT_THROTTLE_RATES": {
#         "user": "1/minute",
#     },
# }
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:4200",
    "https://vai.xob-webservices.com",
    "https://app.vai.gt-ai.io",
    "https://admin.vai.gt-ai.io",
    "https://admin.vai.gt-ai.io",
    "https://admin.vai.gt-ai.io",

    "https://api.app.vai.gt-ai.io",
]
# handler403 = "accounts.views.access_denied"
# handler404 = "accounts.views.oops"
# handler500 = "accounts.views.something_went_wrong"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",   # dev-friendly; tighten later per-view
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "60/minute",  # bump from 1/min for dev sanity
    },
}
# In production:
STATIC_ROOT = BASE_DIR / "staticfiles" 
STATICFILES_DIRS = [BASE_DIR / "static"] 
INSTALLED_APPS += ["rest_framework_simplejwt"]


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ELEVENLABS_API_KEY = env.str("ELEVENLABS_API_KEY")
ELEVENLABS_WEBHOOK_SECRET = env.str("ELEVENLABS_WEBHOOK_SECRET", default="")  # for HMAC validation
STRIPE_WEBHOOK_SECRET=env.str("STRIPE_WEBHOOK_SECRET")
CALL_WINDOW_TZ = "Asia/Riyadh"
CALL_WINDOW_START_HOUR = 9
CALL_WINDOW_END_HOUR = 15
CAMPAIGN_MAX_PARALLEL_CALLS = 1
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="redis://127.0.0.1:6379/0")

CELERY_TIMEZONE = "Asia/Riyadh"
CELERY_ENABLE_UTC = False
CELERY_BEAT_SCHEDULE = {
    "dispatch-campaign-calls": {
        "task": "vai.campaigns.tasks.dispatch_campaign_calls",
        "schedule": crontab(minute="*/5"),
    },
    "cleanup-stale-dispatched-calls": {
        "task": "vai.campaigns.tasks.cleanup_stale_dispatched_calls",
        "schedule": crontab(minute="*/5"),
    },
}
CHECKOUT_SUCCESS_URL = os.getenv('CHECKOUT_SUCCESS_URL', 'https://app.vai.gt-ai.io/Account')
CHECKOUT_CANCEL_URL  = os.getenv('CHECKOUT_CANCEL_URL',  'https://app.vai.gt-ai.io/Account')
PORTAL_RETURN_URL    = os.getenv('PORTAL_RETURN_URL',    'https://app.vai.gt-ai.io/Account')

STRIPE_PORTAL_CONFIGURATION_ID = os.getenv('STRIPE_PORTAL_CONFIGURATION_ID', None)