# Generated by Django 5.2.5 on 2025-09-25 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('lists', '0001_initial'),
        ('phone_numbers', '0001_initial'),
        ('voices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prompt', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('started', 'Started'), ('stopped', 'Stopped')], default='stopped', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='voices.agent')),
                ('lead_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='lists.leadlist')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='phone_numbers.phonenumberrequest')),
                ('voice_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='voices.voiceprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('positive', 'Positive'), ('negative', 'Negative'), ('dnc', 'Do Not Call')], default='new', max_length=16)),
                ('call_count', models.IntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('first_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_leads', to='campaigns.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_leads', to='leads.lead')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='leads',
            field=models.ManyToManyField(related_name='campaigns', through='campaigns.CampaignLead', to='leads.lead'),
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='twilio', max_length=32)),
                ('provider_conversation_id', models.CharField(blank=True, max_length=128, null=True)),
                ('provider_call_id', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('dispatched', 'Dispatched'), ('ringing', 'Ringing'), ('no_answer', 'No Answer'), ('answered', 'Answered'), ('completed', 'Completed'), ('failed', 'Failed')], default='dispatched', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='calls/outbound/')),
                ('transcript_text', models.TextField(blank=True, default='')),
                ('transcript_json', models.JSONField(blank=True, null=True)),
                ('analysis', models.JSONField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_positive', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_logs', to='voices.agent')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='leads.lead')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_logs', to='phone_numbers.phonenumberrequest')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'created_at'], name='campaigns_c_owner_i_04330c_idx'), models.Index(fields=['campaign', 'created_at'], name='campaigns_c_campaig_05f906_idx'), models.Index(fields=['lead', 'created_at'], name='campaigns_c_lead_id_548346_idx'), models.Index(fields=['status'], name='campaigns_c_status_419a65_idx'), models.Index(fields=['provider_conversation_id'], name='campaigns_c_provide_df6d90_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='campaignlead',
            index=models.Index(fields=['campaign', 'status'], name='campaigns_c_campaig_887c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignlead',
            index=models.Index(fields=['campaign', 'updated_at'], name='campaigns_c_campaig_5de842_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignlead',
            index=models.Index(fields=['campaign', 'last_attempted_at'], name='campaigns_c_campaig_e83a46_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignlead',
            unique_together={('campaign', 'lead')},
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['owner', 'created_at'], name='campaigns_c_owner_i_05aea8_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['owner', 'name'], name='campaigns_c_owner_i_989fde_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='campaigns_c_status_96cb56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('owner', 'name')},
        ),
    ]
