# Generated by Django 5.2.5 on 2025-09-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('stopped', 'Stopped'), ('completed', 'Completed')], default='stopped', max_length=16),
        ),
    ]
