# Generated by Django 5.2.5 on 2025-12-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='dispatch_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calllog',
            name='dispatch_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
