# Generated by Django 5.2.5 on 2025-09-30 09:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BundlePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, help_text='Recurring price in currency units (e.g. USD). Use 0.00 for free trials.', max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('billing_interval', models.CharField(choices=[('month', 'Monthly')], default='month', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_trial', models.BooleanField(default=False, help_text='Mark as a trial plan (price often 0).')),
                ('trial_period_days', models.PositiveIntegerField(default=0, help_text='Optional: use to set trial period on subscription creation.')),
                ('stripe_product_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('auto_sync_to_stripe', models.BooleanField(default=True)),
                ('sa_minutes', models.PositiveIntegerField(default=0)),
                ('sa_unlimited_minutes', models.BooleanField(default=False)),
                ('sa_extra_per_minute', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10)),
                ('sa_customizations_enabled', models.BooleanField(default=False)),
                ('oc_minutes', models.PositiveIntegerField(default=0)),
                ('oc_extra_per_minute', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10)),
                ('oc_can_use_vai_database', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutboundCallingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, help_text='Recurring price in currency units (e.g. USD). Use 0.00 for free trials.', max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('billing_interval', models.CharField(choices=[('month', 'Monthly')], default='month', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_trial', models.BooleanField(default=False, help_text='Mark as a trial plan (price often 0).')),
                ('trial_period_days', models.PositiveIntegerField(default=0, help_text='Optional: use to set trial period on subscription creation.')),
                ('stripe_product_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('auto_sync_to_stripe', models.BooleanField(default=True)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('extra_per_minute', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10)),
                ('can_use_vai_database', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportAgentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, help_text='Recurring price in currency units (e.g. USD). Use 0.00 for free trials.', max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('billing_interval', models.CharField(choices=[('month', 'Monthly')], default='month', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_trial', models.BooleanField(default=False, help_text='Mark as a trial plan (price often 0).')),
                ('trial_period_days', models.PositiveIntegerField(default=0, help_text='Optional: use to set trial period on subscription creation.')),
                ('stripe_product_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('auto_sync_to_stripe', models.BooleanField(default=True)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('unlimited_minutes', models.BooleanField(default=False)),
                ('extra_per_minute', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10)),
                ('customizations_enabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_object_id', models.PositiveIntegerField()),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('latest_invoice_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete (Expired)'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('paused', 'Paused')], default='incomplete', max_length=32)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('plan_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsageBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.CharField(choices=[('support_agent', 'Support Agent'), ('outbound_calling', 'Outbound Calling')], max_length=32)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('seconds_included', models.PositiveIntegerField(default=0)),
                ('seconds_used', models.PositiveIntegerField(default=0)),
                ('unlimited', models.BooleanField(default=False)),
                ('extra_per_minute', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_buckets', to='billing.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.CharField(choices=[('support_agent', 'Support Agent'), ('outbound_calling', 'Outbound Calling')], max_length=32)),
                ('seconds', models.PositiveIntegerField()),
                ('at_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='billing.subscription')),
            ],
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='billing_sub_user_id_fe5b98_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan_content_type', 'plan_object_id'], name='billing_sub_plan_co_0371d8_idx'),
        ),
        migrations.AddIndex(
            model_name='usagebucket',
            index=models.Index(fields=['subscription', 'component'], name='billing_usa_subscri_d68f10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usagebucket',
            unique_together={('subscription', 'component', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['subscription', 'component', 'at_time'], name='billing_usa_subscri_dc5a35_idx'),
        ),
    ]
