# Generated by Django 5.2.5 on 2025-10-06 07:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_paymentmethod'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_item_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='BillingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=150)),
                ('kind', models.CharField(choices=[('purchase', 'purchase'), ('upgrade', 'upgrade'), ('renewal', 'renewal'), ('overage', 'overage'), ('topup', 'topup'), ('cancel', 'cancel')], max_length=32)),
                ('status', models.CharField(choices=[('initiated', 'initiated'), ('pending', 'pending'), ('requires_action', 'requires_action'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('canceled', 'canceled')], default='initiated', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('stripe_invoice_url', models.URLField(blank=True, null=True)),
                ('stripe_invoice_pdf', models.URLField(blank=True, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('failure_code', models.CharField(blank=True, max_length=128)),
                ('failure_message', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('plan_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'kind', 'status'], name='billing_bil_user_id_7bc520_idx'), models.Index(fields=['subscription', 'kind'], name='billing_bil_subscri_e9caa1_idx')],
            },
        ),
    ]
