# Generated by Django 5.2.5 on 2025-10-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_subscription_cancel_at_period_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingtransaction',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
